language: c
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository -y ppa:vala-team/ppa
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq valac cmake libgtk-3-dev check libjson-glib-dev libsqlite3-dev yasm > /dev/null

before_script:
  #installing libsodium, needed for Core
  - _libsodium_ver=0.4.5
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - pushd libsodium
  - git checkout tags/${_libsodium_ver} > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure --prefix=/usr > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd
  #installing libopus, needed for audio encoding/decoding
  - wget http://downloads.xiph.org/releases/opus/opus-1.0.3.tar.gz > /dev/null
  - tar xzf opus-1.0.3.tar.gz > /dev/null
  - pushd opus-1.0.3
  - ./configure --prefix=/usr > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd
  #installing vpx
  - git clone http://git.chromium.org/webm/libvpx.git > /dev/null
  - pushd libvpx
  - ./configure --prefix=/usr > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd
  #installing toxcore
  - git clone http://github.com/irungentoo/ProjectTox-Core.git > /dev/null
  - pushd ProjectTox-Core
  - autoreconf -i > /dev/null
  - ./configure --prefix=/usr --disable-testing --disable-ntox --disable-dht-bootstrap-daemon > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd
  #creating libraries links and updating cache
  - sudo ldconfig > /dev/null

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j3
  - sudo make install
